// agents/dashboard/lib/creatives-store.js
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { CREATIVE_SESSIONS_DIR, CREATIVES_DIR } from './paths.js';
import { ensureDir } from './fs-helpers.js';

export const GEMINI_MODELS = [
  { id: 'gemini-3.1-flash-image-preview', name: 'Gemini 3.1 Flash', maxReferenceImages: 16, resolutions: ['512', '1K', '2K', '4K'] },
  { id: 'gemini-3-pro-image-preview', name: 'Gemini 3 Pro', maxReferenceImages: 16, resolutions: ['1K', '2K', '4K'] },
  { id: 'gemini-2.5-flash-image', name: 'Gemini 2.5 Flash', maxReferenceImages: 10, resolutions: ['1K'] },
];

export function saveSession(session) {
  session.updatedAt = new Date().toISOString();
  const filePath = join(CREATIVE_SESSIONS_DIR, session.id + '.json');
  writeFileSync(filePath, JSON.stringify(session, null, 2));
  return session;
}

export function createSession() {
  const id = 'session-' + Date.now() + '-' + Math.random().toString(36).slice(2, 8);
  const session = {
    id,
    name: 'New Session',
    nameAutoGenerated: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    model: GEMINI_MODELS[0].id,
    templateId: null,
    prompt: '',
    negativePrompt: '',
    aspectRatio: '1:1',
    referenceImages: [],
    versions: []
  };
  ensureDir(join(CREATIVES_DIR, id));
  return saveSession(session);
}
