#!/usr/bin/env bash
# Rebuild the five replacement PDP frames from the archived originals.
#
# Companion to scripts/publish-forbidden-ingredient-frames.mjs — read its header
# for WHY. This file records HOW, with every coordinate measured rather than
# guessed, so the replacements can be regenerated byte-for-byte-equivalent if
# they are ever lost.
#
# Nothing here calls an image model. Every frame is its original pixels with rows
# erased, moved, or (lotion, cream only) one or two rows typeset in a measured
# face. The product in each frame is untouched.
#
# Requires ImageMagick 7, python3 (for a throwaway fonttools venv) and network
# access to raw.githubusercontent.com for the two OFL fonts.
#
# Usage: scripts/compose-forbidden-ingredient-frames.sh
set -euo pipefail

IN=data/archive/forbidden-ingredient-frames-2026-09-10
OUT=data/creatives/forbidden-ingredient-frames
T=$(mktemp -d)
mkdir -p "$OUT"

# ── Fonts ──────────────────────────────────────────────────────────────────────
# Measured against the originals at matched cap height:
#   lotion rows  → Inter ExtraBold (opsz 32): "No" 112 vs 110px, "parabens" 392 vs 393px
#   cream rows   → Outfit 700 for "No"; Outfit 500 + 2.3px tracking for the word:
#                  "lanolin" 199 vs 199px, "parabens" 290 vs 290px, 'l' stem 7 vs 7px
python3 -m venv "$T/venv" >/dev/null && "$T/venv/bin/pip" install -q fonttools
curl -sL -o "$T/Inter.ttf"  "https://raw.githubusercontent.com/google/fonts/main/ofl/inter/Inter%5Bopsz,wght%5D.ttf"
curl -sL -o "$T/Outfit.ttf" "https://raw.githubusercontent.com/google/fonts/main/ofl/outfit/Outfit%5Bwght%5D.ttf"
"$T/venv/bin/python" -m fontTools.varLib.instancer "$T/Inter.ttf"  wght=800 opsz=32 -o "$T/Inter-800.ttf" -q
"$T/venv/bin/python" -m fontTools.varLib.instancer "$T/Outfit.ttf" wght=500 -o "$T/Outfit-500.ttf" -q
"$T/venv/bin/python" -m fontTools.varLib.instancer "$T/Outfit.ttf" wght=700 -o "$T/Outfit-700.ttf" -q

offset() { # font pointsize text [kerning] → "X Y" ink offset inside an untrimmed label canvas
  magick -background white -fill black -font "$1" -pointsize "$2" -kerning "${4:-0}" label:"$3" -trim -format '%X %Y' info: | tr -d '+'
}

# ── Deodorant (1400²): drop row 4 "No petrolatum or dimethicone"; rows 1-3 down 80px ──
# The erase narrows to x645 below y960 so the left bottle's base shadow (x645-688) is kept.
D=$IN/coconut-oil-deodorant/deodorant-not-in-it.png
magick "$D" -crop 600x520+60+390 +repage "$T/deo-block.png"
magick "$D" -fill white -draw "rectangle 60,380 668,960" -draw "rectangle 60,960 645,1136" "$T/deo-blank.png"
magick "$T/deo-blank.png" "$T/deo-block.png" -geometry +60+470 -composite -alpha off "$OUT/deodorant-not-in-it-v2.png"

# ── Lip balm (1400²): drop row 1 "No petrolatum"; rows 2-4 up 125px ──
L=$IN/coconut-oil-lip-balm/lip-balm-not-in-it.png
magick "$L" -crop 880x665+130+600 +repage "$T/lip-block.png"
magick "$L" -fill white -draw "rectangle 125,335 1040,1275" "$T/lip-blank.png"
magick "$T/lip-blank.png" "$T/lip-block.png" -geometry +130+475 -composite -alpha off "$OUT/lip-balm-not-in-it-v2.png"

# ── Lotion (1400²): mineral oil / petrolatum / dimethicone rows → "No silicones",
#    "No synthetic / fragrance"; original "No parabens" row kept. Both new claims are
#    in the live coconut-lotion body ("no silicones, no synthetic fragrance").
#    Original rows: X-mark ink tops 381/606/831/1055 (pitch 225); N cap top = X top + 33;
#    N left edge x265. New X tops 436 / 661 / 991, wrapped line +105px.
O=$IN/coconut-lotion/lotion-not-in-it.png
FONT="$T/Inter-800.ttf"; PT=89; INK="rgb(8,10,8)"
read -r NX NY <<< "$(offset "$FONT" $PT No)"
magick "$O" -fill white -draw "rectangle 55,365 962,1205" "$T/lotion-blank.png"
magick "$O" -crop 190x160+60+1040 +repage "$T/xmark.png"
magick "$O" -crop 900x160+60+1040 +repage "$T/parabens-row.png"
for t in "No silicones" "No synthetic" "fragrance"; do
  magick -background none -fill "$INK" -font "$FONT" -pointsize $PT label:"$t" "$T/t_${t// /_}.png"
done
magick "$T/lotion-blank.png" \
  "$T/xmark.png"          -geometry +60+422                         -composite \
  "$T/t_No_silicones.png" -geometry +$((265-NX))+$((436+33-NY))     -composite \
  "$T/xmark.png"          -geometry +60+647                         -composite \
  "$T/t_No_synthetic.png" -geometry +$((265-NX))+$((661+33-NY))     -composite \
  "$T/t_fragrance.png"    -geometry +$((265-NX))+$((661+33-NY+105)) -composite \
  "$T/parabens-row.png"   -geometry +60+977                         -composite \
  -alpha off "$OUT/lotion-not-in-it-v2.png"

# ── Body cream (1400²): petrolatum / dimethicone rows → "No synthetic / fragrance"
#    (the live coconut-moisturizer body says "no synthetic fragrance"); original
#    lanolin and parabens rows kept, moved up 33px. The cream swatch sits under the
#    old rows at x>=620 below y786, so the erase stops at x605 there.
#    Original lanolin row: X ink top 848, N cap top 865, N left x211, word left x312, cap 46px.
C=$IN/coconut-moisturizer/body-cream-not-in-it.png
R="$T/Outfit-500.ttf"; B="$T/Outfit-700.ttf"; PR=65.714; PB=65.018; KERN=2.3; CINK="rgb(22,24,18)"
read -r BNX BNY <<< "$(offset "$B" $PB No)"
read -r _   RNY <<< "$(offset "$R" $PR N)"
read -r SX  _   <<< "$(offset "$R" $PR synthetic $KERN)"
read -r GX  _   <<< "$(offset "$R" $PR fragrance $KERN)"
A1=610; BASE1=$((A1+46)); BASE2=$((BASE1+72))
magick "$C" -fill white -draw "rectangle 60,540 700,770" -draw "rectangle 60,770 684,786" -draw "rectangle 60,786 605,1095" "$T/cream-blank.png"
magick "$C" -crop 545x110+60+835 +repage "$T/lanolin-row.png"
magick "$C" -crop 545x105+60+985 +repage "$T/cream-parabens-row.png"
magick "$C" -crop 150x110+60+835 +repage "$T/cream-x.png"
magick -background none -fill "$CINK" -font "$B" -pointsize $PB label:No -channel A -blur 0x0.5 +channel "$T/c_no.png"
magick -background none -fill "$CINK" -font "$R" -pointsize $PR -kerning $KERN label:synthetic -channel A -blur 0x0.5 +channel "$T/c_syn.png"
magick -background none -fill "$CINK" -font "$R" -pointsize $PR -kerning $KERN label:fragrance -channel A -blur 0x0.5 +channel "$T/c_fra.png"
magick "$T/cream-blank.png" \
  "$T/lanolin-row.png"        -geometry +60+802                                -composite \
  "$T/cream-parabens-row.png" -geometry +60+952                                -composite \
  "$T/cream-x.png"            -geometry +60+$((835 + A1 - 865))                -composite \
  "$T/c_no.png"               -geometry +$((211-BNX))+$((A1-BNY))              -composite \
  "$T/c_syn.png"              -geometry +$((312-SX))+$((BASE1-RNY-46))         -composite \
  "$T/c_fra.png"              -geometry +$((312-GX))+$((BASE2-RNY-46))         -composite \
  -alpha off "$OUT/body-cream-not-in-it-v2.png"

# ── Lotion compare (2000²): drop row 2 "No mineral oil or petrolatum". ──
#    Rules at y241/421/600/780/960, divider x999. Row 3 content (y602-779) moves up
#    180; row 4 content (y782-959) moves up 180 with its centre strip (the bottle cap,
#    x912-1088) swapped for row 3's cap-free centre strip. The vacated band y782-963 is
#    filled with a per-column vertical gradient between clean rows above and below —
#    the background measures std 0.33, so no grain is added (adding grain produced
#    ghost letterforms). Only the cap body itself (x916-1084, from its top at y800) is
#    kept from the original, which also removes the divider stub below the new bottom
#    rule and the old rule stubs beside the cap.
K=$IN/coconut-lotion/clean-compare.jpg
magick "$K" -crop 2000x178+0+602 +repage "$T/r3.png"
magick "$K" -crop 2000x178+0+782 +repage "$T/r4.png"
magick "$K" -crop 176x178+912+602 +repage "$T/centre.png"
magick "$T/r4.png" "$T/centre.png" -geometry +912+0 -composite "$T/r4c.png"
magick "$K" "$T/r3.png" -geometry +0+422 -composite "$T/r4c.png" -geometry +0+602 -composite "$T/cmp-AB.png"
magick "$T/cmp-AB.png" -crop 2000x5+0+770 +repage -scale '2000x1!' "$T/top.png"
magick "$K" -crop 2000x5+0+966 +repage -scale '2000x1!' "$T/bot.png"
magick "$T/bot.png" \( "$T/bot.png" -crop 60x1+850+0 +repage -scale '168x1!' \) -geometry +916+0 -composite "$T/bot.png"
magick "$T/top.png" "$T/bot.png" -append -filter Triangle -resize '2000x182!' "$T/grad.png"
magick -size 2000x182 xc:white -fill black -draw "rectangle 916,18 1084,172" -draw "rectangle 920,173 1080,181" "$T/mask.png"
magick "$T/cmp-AB.png" \( "$T/cmp-AB.png" -crop 2000x182+0+782 +repage "$T/grad.png" "$T/mask.png" -composite \) \
  -geometry +0+782 -composite -quality 95 "$OUT/clean-compare-v2.jpg"

rm -rf "$T"
ls -la "$OUT"
