#!/bin/bash
# setup-cron.sh — Install system cron jobs for the SEO pipeline
#
# Run once to register all recurring tasks:
#   chmod +x scripts/setup-cron.sh && ./scripts/setup-cron.sh
#
# Jobs installed:
#   Daily   08:00 PT — scheduler (publish-due + next pipeline item)
#   Daily   06:00 PT — blog-index refresh
#   Weekly  Mon 07:00 PT — rank tracker snapshot
#   Weekly  Mon 07:30 PT — insight aggregator
#   Weekly  Mon 06:00 PT — topical map refresh
#   Daily   06:00 PT — clarity-collector (CRO)
#   Daily   06:05 PT — shopify-collector (CRO)
#   Weekly  Mon 07:45 PT — cro-analyzer
#   Daily   06:45 PT — ads-optimizer
#   Weekly  Sun 07:00 PT — ads-weekly-recap
#   Daily   05:00 PST — daily summary digest email

set -e

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
NODE="$(which node)"

mkdir -p "$PROJECT_DIR/data/reports"
mkdir -p "$PROJECT_DIR/data/reports/scheduler"

echo "Project: $PROJECT_DIR"
echo "Node:    $NODE"
echo ""

# Build new cron entries
DAILY_SCHEDULER="0 8 * * * cd \"$PROJECT_DIR\" && $NODE scheduler.js >> data/reports/scheduler/scheduler.log 2>&1"
DAILY_BLOG_INDEX="0 6 * * * cd \"$PROJECT_DIR\" && $NODE agents/blog-content/index.js list >> data/reports/scheduler/blog-index.log 2>&1"
WEEKLY_RANK_TRACKER="0 7 * * 1 cd \"$PROJECT_DIR\" && $NODE agents/rank-tracker/index.js >> data/reports/scheduler/rank-tracker.log 2>&1"
WEEKLY_INSIGHTS="30 7 * * 1 cd \"$PROJECT_DIR\" && $NODE agents/insight-aggregator/index.js >> data/reports/scheduler/insights.log 2>&1"
WEEKLY_TOPICAL_MAP="0 6 * * 1 cd \"$PROJECT_DIR\" && $NODE agents/topical-mapper/index.js >> data/reports/scheduler/topical-map.log 2>&1"
DAILY_CLARITY="0 13 * * * cd \"$PROJECT_DIR\" && $NODE agents/clarity-collector/index.js >> data/reports/scheduler/clarity-collector.log 2>&1"
DAILY_SHOPIFY="5 13 * * * cd \"$PROJECT_DIR\" && $NODE agents/shopify-collector/index.js >> data/reports/scheduler/shopify-collector.log 2>&1"
DAILY_GSC="15 13 * * * cd \"$PROJECT_DIR\" && $NODE agents/gsc-collector/index.js >> data/reports/scheduler/gsc-collector.log 2>&1"
DAILY_GA4="20 13 * * * cd \"$PROJECT_DIR\" && $NODE agents/ga4-collector/index.js >> data/reports/scheduler/ga4-collector.log 2>&1"
DAILY_GOOGLE_ADS="25 13 * * * cd \"$PROJECT_DIR\" && $NODE agents/google-ads-collector/index.js >> data/reports/scheduler/google-ads-collector.log 2>&1"
WEEKLY_CRO_ANALYZER="45 14 * * 1 cd \"$PROJECT_DIR\" && $NODE agents/cro-analyzer/index.js >> data/reports/scheduler/cro-analyzer.log 2>&1"
DAILY_ADS_OPTIMIZER="45 6 * * * TZ=America/Los_Angeles cd \"$PROJECT_DIR\" && $NODE agents/ads-optimizer/index.js >> data/reports/ads-optimizer.log 2>&1"
WEEKLY_ADS_RECAP="0 7 * * 0 TZ=America/Los_Angeles cd \"$PROJECT_DIR\" && $NODE scripts/ads-weekly-recap.js >> data/reports/ads-weekly-recap.log 2>&1"
DAILY_RANK_ALERTER="30 13 * * * cd \"$PROJECT_DIR\" && $NODE agents/rank-alerter/index.js >> data/reports/scheduler/rank-alerter.log 2>&1"
DAILY_PIPELINE_SCHEDULER="0 15 * * * cd \"$PROJECT_DIR\" && $NODE agents/pipeline-scheduler/index.js >> data/reports/scheduler/pipeline-scheduler.log 2>&1"
WEEKLY_META_AB_TRACKER="0 15 * * 1 cd \"$PROJECT_DIR\" && $NODE agents/meta-ab-tracker/index.js >> data/reports/scheduler/meta-ab-tracker.log 2>&1"
AHREFS_REMINDER="0 7 * * 0 cd \"$PROJECT_DIR\" && $NODE scripts/ahrefs-reminder.js >> data/reports/scheduler/ahrefs-reminder.log 2>&1"
DAILY_CAMPAIGN_MONITOR="30 7 * * * TZ=America/Los_Angeles cd \"$PROJECT_DIR\" && $NODE agents/campaign-monitor/index.js >> data/reports/campaign-monitor.log 2>&1"
WEEKLY_CAMPAIGN_ANALYZER="0 6 * * 0 TZ=America/Los_Angeles cd \"$PROJECT_DIR\" && $NODE agents/campaign-analyzer/index.js >> data/reports/campaign-analyzer.log 2>&1"
BIWEEKLY_STRATEGIST="0 12 * * 0 [ \$(( \$(date +%W) % 2 )) -eq 0 ] && cd \"$PROJECT_DIR\" && $NODE agents/content-strategist/index.js >> data/reports/scheduler/content-strategist.log 2>&1"
DAILY_SUMMARY="0 13 * * * cd \"$PROJECT_DIR\" && $NODE agents/daily-summary/index.js >> data/logs/daily-summary.log 2>&1"

# Read existing crontab (ignore error if none exists)
EXISTING=$(crontab -l 2>/dev/null || true)

# Strip any previous entries for this project to avoid duplicates
CLEANED=$(echo "$EXISTING" | grep -v "$PROJECT_DIR" || true)

# Append new entries
NEW_CRONTAB="$CLEANED
# SEO Pipeline — auto-generated by setup-cron.sh
$DAILY_SCHEDULER
$DAILY_BLOG_INDEX
$AHREFS_REMINDER
$WEEKLY_RANK_TRACKER
$WEEKLY_INSIGHTS
$WEEKLY_TOPICAL_MAP
$DAILY_CLARITY
$DAILY_SHOPIFY
$DAILY_GSC
$DAILY_GA4
$DAILY_GOOGLE_ADS
$WEEKLY_CRO_ANALYZER
$DAILY_ADS_OPTIMIZER
$WEEKLY_ADS_RECAP
$DAILY_RANK_ALERTER
$DAILY_PIPELINE_SCHEDULER
$WEEKLY_META_AB_TRACKER
$DAILY_CAMPAIGN_MONITOR
$WEEKLY_CAMPAIGN_ANALYZER
$BIWEEKLY_STRATEGIST
$DAILY_SUMMARY
"

echo "Installing cron jobs..."
echo "$NEW_CRONTAB" | crontab -

echo ""
echo "Installed:"
echo "  Daily   08:00 PT — scheduler (publish-due + next pipeline item)"
echo "  Daily   06:00 PT — blog-index refresh"
echo "  Weekly  Sun 07:00 UTC — Ahrefs upload reminder"
echo "  Weekly  Mon 07:00 PT — rank tracker snapshot"
echo "  Weekly  Mon 07:30 PT — insight aggregator"
echo "  Weekly  Mon 06:00 PT — topical map refresh"
echo "  Daily   06:00 PT — clarity-collector (CRO)"
echo "  Daily   06:05 PT — shopify-collector (CRO)"
echo "  Daily   06:15 PDT / 05:15 PST — gsc-collector"
echo "  Daily   06:20 PDT / 05:20 PST — ga4-collector"
echo "  Daily   06:25 PDT / 05:25 PST — google-ads-collector"
echo "  Weekly  Mon 07:45 PT — cro-analyzer"
echo "  Daily   06:45 PT — ads-optimizer (alert email if suggestions)"
echo "  Weekly  Sun 07:00 PT — ads-weekly-recap"
echo "  Daily   13:30 UTC — rank-alerter (after GSC collector)"
echo "  Daily   15:00 UTC — pipeline-scheduler"
echo "  Weekly  Mon 15:00 UTC — meta-ab-tracker"
echo "  Daily   07:30 PT — campaign-monitor"
echo "  Weekly  Sun 06:00 PT — campaign-analyzer"
echo "  Daily   05:00 PST (13:00 UTC) — daily summary digest email"
echo "  Bi-weekly Sun 05:00 PT — content-strategist calendar refresh"
echo ""
echo "View with: crontab -l"
echo "Logs in:   $PROJECT_DIR/data/reports/scheduler/"
